### ISSUE TITLE
请教lib_da87d53.js的未压缩代码

### ISSUE THREAD

**Issue by tangguangyao** [scrat-team/scrat-team.github.io#1]
从 http://www.zhihu.com/question/28467444 过来，想参考学习下localstorage 的使用方法。

**Comment by fouber** [comment]
@tangguangyao 
1. 构建配置文件 `fis-conf.js` 中设置：

``` js
// fis-conf.js
fis.config.set('framework.cache', true);
```
1. scrat release中加参数 `-o` ：

```
scrat release -o
```

然后前端框架就会把请求回来的静态资源缓存到localstorage中了
